name: update

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * SUN"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: "main"
    - uses: actions/setup-node@v2
      with:
        node-version: "12"
    - run: |
        echo ${{ secrets.GITHUB_TOKEN }} >> access_token.txt
        node index.js
    - name: update the list
      env:
        GITHUB_USER: "ravener"
        GITHUB_EMAIL: "ravener.anime@gmail.com"
      run: |
        git config user.name "${GITHUB_USER}"
        git config user.email "${GITHUB_EMAIL}"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
        git checkout main
        git commit -am "chore: auto update"
        git push -u origin main
